/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Fish(props) {
    const { nodes, materials } = useGLTF("/Fish.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.g_Handle1.geometry}
                material={materials.Handle1Mtl}
            />
        </group>
    );
}

useGLTF.preload("/Fish.glb");
